appearance:
  default: system
  switcher: true


# base colors https://mycolor.space/?hex=%230777B3&sub=1
theme:
  # colorPalettes:
  #   default:
  #     - "#0777b3"  # Blue
  #     - "#963d97"  # Purple
  #     - "#e03a3e"  # Red
  #     - "#f5821f"  # Orange
  #     - "#fdb827"  # Yellow
  #     - "#61bb46"  # Green
  #     - "#ffcc00"  # Gold
  #     - "#ff7f50"  # Coral
  #     - "#ff6347"  # Tomato
  #     - "#ff4500"  # Orange Red
  #     - "#da70d6"  # Orchid
  colorScales:
    default:
      - "#0777b3"  # Blue
      - "#bd4e35"  # Orange
  colors:
    primary:
      light: "#0777b3"  # Blue
      dark: "#0777b3"  # Blue
    accent:
      light: "#bd4e35"  # Orange
      dark: "#bd4e35"  # Orange
    base:
      light: "#f8f8f8" # Paper
      dark: "#231f20" # Dark
    info:
      light: "#638CAD"  # Blue
      dark: "#638CAD"  # Blue
    warning:
      light: "#e18727"  # Yellow
      dark: "#e18727"  # Yellow
    negative:
      light: "#bc1200"  # Red
      dark: "#bc1200"  # Red
    positive:
      light: "#46b000"  # Green
      dark: "#46b000"  # Green
